// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/catalogo-split-rail/CatalogoSplitRailVariant.tsx": () => import("../components/mockups/catalogo-split-rail/CatalogoSplitRailVariant.tsx"),
  "./components/mockups/construmarket/ConstruMarketRefined.tsx": () => import("../components/mockups/construmarket/ConstruMarketRefined.tsx"),
  "./components/mockups/construmarket/ConstruMarketReviewQueue.tsx": () => import("../components/mockups/construmarket/ConstruMarketReviewQueue.tsx"),
  "./components/mockups/editorial/ConstruMarketEditorial.tsx": () => import("../components/mockups/editorial/ConstruMarketEditorial.tsx")
};
